<a href="https://colab.research.google.com/github/JAYANTHSOLUTIONS/Data-science-/blob/main/Task1_NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

IMPORTING LIBRARY FUNCTIONS

In [ ]:
import numpy as np
import pandas as pd

OPEN AND READING CSV FILES

NUMPY ARRAY OPERATIONS

In [ ]:
#creating arrays
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [ ]:
# creating ones
a=np.ones((2,2))
a

array([[1., 1.],
       [1., 1.]])

In [ ]:
# creating zero arrays
a=np.zeros((2,2))
a

array([[0., 0.],
       [0., 0.]])

In [ ]:
#creating by a range
a=np.arange(1,100,3)
a

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49,
       52, 55, 58, 61, 64, 67, 70, 73, 76, 79, 82, 85, 88, 91, 94, 97])

In [ ]:
a= np.linspace(1,20,10)
a

array([ 1.        ,  3.11111111,  5.22222222,  7.33333333,  9.44444444,
       11.55555556, 13.66666667, 15.77777778, 17.88888889, 20.        ])

In [ ]:
A=np.eye(3,3)
A

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#shape of the array
A.shape

(3, 3)

In [ ]:
# dimesions of an array
A.ndim

2

In [ ]:
# size of an Array
A.size

9

In [ ]:
#type of an Array
A.dtype

dtype('float64')

BASIC ARITHMETIC OPERATIONS

In [ ]:
#adding
B=np.add(A,5)
B

array([[6., 5., 5.],
       [5., 6., 5.],
       [5., 5., 6.]])

In [ ]:
#subtracting
B=np.subtract(A,5)
B

array([[-4., -5., -5.],
       [-5., -4., -5.],
       [-5., -5., -4.]])

In [ ]:
#multiplication
B=np.multiply(B,-1)
B

array([[4., 5., 5.],
       [5., 4., 5.],
       [5., 5., 4.]])

In [ ]:
#division
B=np.divide(B,5)
B

array([[0.8, 1. , 1. ],
       [1. , 0.8, 1. ],
       [1. , 1. , 0.8]])

In [ ]:
#dot operation
C=np.dot(A,B)
C

array([[0.8, 1. , 1. ],
       [1. , 0.8, 1. ],
       [1. , 1. , 0.8]])

In [ ]:
#reshaping of an array
C = C.reshape(9,1)
C

array([[0.8],
       [1. ],
       [1. ],
       [1. ],
       [0.8],
       [1. ],
       [1. ],
       [1. ],
       [0.8]])

In [ ]:
#concatenating two arrays using concatenate function
A= np.array([1,2,3])
C = np.array([4,5,6])
D=np.concatenate((A,C),axis=0)

In [ ]:
#splitting
D=np.split(D,2)
D

[array([1, 2, 3]), array([4, 5, 6])]

In [ ]:
#transpose of an Array
C = np.array([[4,5,6],[7,8,9]])
C=np.transpose(C)
C

array([[4, 7],
       [5, 8],
       [6, 9]])

MATHEMATICAL OPERATIONS

In [ ]:
#sum
A=np.array([1,2,3,4,5,6,7])
np.sum(A)

28

In [ ]:
#mean
np.mean(A)

4.0

In [ ]:
#median
np.median(A)

4.0

In [ ]:
#standard deviation
np.std(A)

2.0

In [ ]:
#minimum value of an array
np.min(A)

1

In [ ]:
#maximum value of an array
np.max(A)

7

TRIGONOMETRIC FUNCTIONS

In [ ]:
# sin value of an array
np.sin(A)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ])

In [ ]:

#cos value of an array
np.cos(A)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219,
        0.96017029,  0.75390225])

In [ ]:
#tan value of an array
np.tan(A)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128, -3.38051501,
       -0.29100619,  0.87144798])

In [ ]:
#arcsin
np.arcsin(A)

<ipython-input-47-a38cc5dbe0ba>:2: RuntimeWarning: invalid value encountered in arcsin
  np.arcsin(A)


array([1.57079633,        nan,        nan,        nan,        nan,
              nan,        nan])

In [ ]:
#arc cos
np.arccos(A)

<ipython-input-48-a76bdbef20f1>:2: RuntimeWarning: invalid value encountered in arccos
  np.arccos(A)


array([ 0., nan, nan, nan, nan, nan, nan])

In [ ]:
#arc tan
np.arctan(A)

array([0.78539816, 1.10714872, 1.24904577, 1.32581766, 1.37340077,
       1.40564765, 1.42889927])

RANDOM FUNCTIONS

In [ ]:
#random
Z= np.random.rand(2,2)
Z

array([[0.06749965, 0.82309323],
       [0.00448771, 0.47533665]])

In [ ]:
Z=np.random.randn(2,2)
Z

array([[-0.10786942,  0.22757177],
       [ 1.05886331, -0.19270847]])

In [ ]:
#random range
Z=np.random.randint(1,4)
Z

3

In [ ]:
#shuffle
np.random.shuffle([1,2,3])